### ISSUE TITLE
ERR spawn npm ENOENT

### ISSUE THREAD

**Issue by q00u** [nathanhleung/install-peerdeps#123]
>install-peerdeps eslint-plugin-vuetify

```bash
install-peerdeps v3.0.0
ERR spawn npm ENOENT
```

Always `ERR spawn npm ENOENT` for every package I try.

**Comment by nobremarcos95** [comment]
I faced the same issue on windows 10

**Comment by q00u** [comment]
Windows 10 for me too

**Comment by dimitricizov** [comment]
same problem here on windows 10

**Comment by marcelreppi** [comment]
+1

**Comment by RangerCoder99** [comment]
Same here!

**Comment by williandf** [comment]
Same here!

**Comment by nathanhleung** [comment]
Are you facing this issue with v2.0.2?

**Comment by RangerCoder99** [comment]
Nop v2.02 working fine, seems to only happen with the new version here on windows 10

**Comment by karlhorky** [comment]
Some of our students at @upleveled have a similar issue on Windows 10 (but not everyone on Windows 10 has this issue!):

```
ERR spawn yarn ENOENT
```

Will try with version `2.0.2`

**Comment by karlhorky** [comment]
@nathanhleung if there is any debugging that we can do on these machines / setups, let us know.

I used `NODE_DEBUG=child_process` to try to see if it was a borked `PATH`, but `PATH` contains the path to the `yarn` binary.

**Comment by nathanhleung** [comment]
> @nathanhleung if there is any debugging that we can do on these machines / setups, let us know.
> 
> I used `NODE_DEBUG=child_process` to try to see if it was a borked `PATH`, but `PATH` contains the path to the `yarn` binary.

Thanks, I'm on macOS so I can't test directly. Could you try `git bisect`ing and running `install-peerdeps` (or just the tests) between commit 5a9cc30c5035c3ccab87ccb53a228cd3a8d26540 and c695ca73c46073c2eaaeb2986cbf0741175161e6 and let me know if you can figure out the bad commit?

**Comment by karlhorky** [comment]
Ok, so @thomalexg and I found two different bugs during bisecting:

## Bug 1: `ERR spawn yarn ENOENT`

```
install-peerdeps v3.0.0
ERR spawn yarn ENOENT
```

First bad commit is 1b386d5015e17309162e8e6bb419bf73b2f27ac9:

```
1b386d5015e17309162e8e6bb419bf73b2f27ac9 is the first bad commit
commit 1b386d5015e17309162e8e6bb419bf73b2f27ac9
Author: Anthony McLin <git@anthonymclin.com>
Date:   Fri May 1 16:37:47 2020 -0700
    feat: use package manager to find peerDependencies
    Fixes #73
    Removes a bunch of custom logic and leverages the "info"
    command that all package managers provide for getting package
    details from a remote registry. By using the package tool, we can
    delegate proxy configs, private registry paths, and auth tokens
    to the package manager. This is especially valuable in networks
    that require complex proxy configurations, or when packages
    have peerDependencies that may be in multiple other private
    than the singular one that was specified
    BREAKING_CHANGE: removes `--registry` `--auth` and `--proxy` options
    Use `.npmrc` or `.yarnrc` to mange private registry paths, auth tokens, and proxy configs
 README.md                    |  31 +-------
 src/cli.js                   |  27 +------
 src/cli.test.js              |   1 -
 src/install-peerdeps.js      | 171 +++++++++++++++++--------------------------
 src/install-peerdeps.test.js |  17 +----
 5 files changed, 70 insertions(+), 177 deletions(-)
```


## Bug 2: `registry.substr` is not a function

```
$ yarn build && node . --yarn --dev @upleveled/eslint-config-upleveled && git reset --hard HEAD
yarn run v1.22.5
$ npm run clean
> install-peerdeps@2.0.3 clean
> rimraf lib
$ babel src --out-dir lib --ignore *.test.js
Successfully compiled 9 files with Babel (2152ms).
✨  Done in 4.25s.
install-peerdeps v2.0.3
C:\Users\Saturn\Desktop\p\install-peerdeps\lib\cli.js:135
  if (registry.substr(-1) === "/") {
               ^
TypeError: registry.substr is not a function
    at Object.<anonymous> (C:\Users\Saturn\Desktop\p\install-peerdeps\lib\cli.js:135:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
Thomas@Thomas MINGW64 ~/Desktop/p/install-peerdeps ((770b881...)|BISECTING)
```

First bad commit is e88f3f1a6a12124d0b64338f3c58b5648cb198d7:

```
e88f3f1a6a12124d0b64338f3c58b5648cb198d7 is the first bad commit
commit e88f3f1a6a12124d0b64338f3c58b5648cb198d7
Author: Anthony McLin <git@anthonymclin.com>
Date:   Fri May 1 12:42:48 2020 -0700
    feat: option to disable using remote registries when getting peerDeps lists
    `--only-peers` was doing two different things which complicated the need
    for proxy settings. Not only was it flagging whether to install the main
    package with the peers, it was also toggling whether the peerDeps list
    was being generated from a local node_modules vs a remote registry.
    By splitting this into two distinct feature flags, we make behavior clearer,
    and future case of delegating proxy settings to NPM or Yarn instead
    of handling those in the utility.
    BREAKING_CHANGE: `--only-peers` now searches for peerDeps via the registry
    unless `--no-registry` is also specified
    * was: `install-peerdeps <package> --only-peers`
    * now: `install-peerdeps <package> --only-peers --no-registry`
 README.md               | 1 +
 src/cli.js              | 5 +++++
 src/install-peerdeps.js | 4 +++-
 3 files changed, 9 insertions(+), 1 deletion(-)
```

**Comment by ljharb** [comment]
Sounds like one of those changes failed to account for `registry` being undefined (which means it should fall back to a hardcoded value of the public npm registry, or yarn’s alias).

**Comment by nathanhleung** [comment]
Thanks for the detailed logs @karlhorky — it looks like bug 2 shouldn't be a problem anymore since we removed the registry option. I'm going to look into bug 1 and commit 1b386d5015e17309162e8e6bb419bf73b2f27ac9 and get back to you.

**Comment by nathanhleung** [comment]
Hi @karlhorky, opened #124 which I think should fix but can't test on macOS. Could you `git fetch` and then `git checkout nathanhleung-fix` and let me know whether it works?

**Comment by karlhorky** [comment]
Cool, thanks! Sure, @thomalexg and I will take a look on his Windows machine tomorrow.

**Comment by karlhorky** [comment]
Confirmed, [the fix works](https://github.com/nathanhleung/install-peerdeps/pull/124#issuecomment-768895250)!

**Comment by karlhorky** [comment]
Nice, this is available now in `3.0.1`. Thanks @nathanhleung !!

**Comment by kirlat** [comment]
Thanks @nathanhleung for providing a fix! v3.0.1, still does not work for me, but the output is different this time.

I'm using `install-peerdeps` with `npx` on Win10, and here is how I'm running it:
`npx install-peerdeps alpheios-node-build --dev --only-peers`
and the output in my case is
`ERR undefined`.

That's different from v3.0.0 where the output is `ERR spawn npm ENOENT` so things have changed since then.

If I run it as `npx install-peerdeps@v2.0.2 alpheios-node-build --dev --only-peers` it works without a hitch. 

My node version is 14.8.0 and npm is 6.14.7.

I will try to test it in different scenarios (maybe installed locally) to get more info on this. Not sure what's the best way to diagnose the issue.

**Comment by karlhorky** [comment]
@kirlat what does it show you if you run this one?

```
npx install-peerdeps alpheios-node-build --dev --only-peers --dry-run
```

**Comment by nathanhleung** [comment]
Thanks @kirlat for the issue and @karlhorky for the comment — this looks like something different than what was described in #123, so I created #128 to continue discussion
